# Generated by Django 4.2.14 on 2024-08-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0009_alter_studentenquirymodel_studying_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="m_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Mother Name"
            ),
        ),
    ]
